### ISSUE TITLE
Convert Barcodes to Image

### ISSUE THREAD

**Issue by abidkhanpk** [team-moeller/better-access-barcode#32]
Hello,

Tha ks for this beautiful utility. One thing I want added into it is ability to convert created barcodes into image as most of the times barcodes are created to be used on the printable reports but reports don't support web browser control which means barcodes can't be used on the reports. I think adding ability to save barcodes into image will be useful addition.

Best Regards

**Comment by team-moeller** [comment]
Hi @PacManPk ,
Your request is understandable to me. However, I myself will not invest a lot of effort here, as I clearly see the future with the Edge browser control, and this can be used in reports.
What you can do is the following: In the Better Access Charts project I supported its use in reports by saving the generated chart as a graphic. I then displayed this graphic in a report. You could adapt this solution for Better Access Barcode.
I wish you much success!

**Comment by abidkhanpk** [comment]
Ok, thanks a lot.
